### ISSUE TITLE
Hexcasting breaks when in a nested fabric mod

### ISSUE THREAD

**Issue by BlastBolt5** [FallingColors/HexMod#191]
I'm trying to put together a modpack without using curseforge by using the nesting mechanic of fabric mods but while the other 90 mods work hexcasting just breaks and won't load in, even when nested alone. I know nesting isn't really supported but I'm just curious why this mod is the only one that has problems

**Comment by object-Object** [comment]
Not really sure what this means or why it would be necessary. There's also not much we can do without version numbers, repro steps, and a crash report. Please open a new issue with that information if this is still a problem.
