### ISSUE TITLE
Fabric versions of Hex Casting + Farmer's Delight causes datapack error

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [FallingColors/HexMod#253]
### Log
https://gist.github.com/GameGuruGreenGryphon/35325cd3b46e17835896db2dbd9aba91
### Versions
Minecraft: 1.18.2
Fabric Loader: 0.14.9
Cardinal Components API: 4.2.0
Fabric API: 0.58.0+ 1.18.2
Fabric Language Kotlin: 1.8.3+ kotlin.1.7.10
Farmer's Delight: 1.18.2- 1.2.1
Hex Casting: 0.9.4
Patchouli: 1.18.2- 71.1-FABRIC
PAUCAL: 0.4.7
### The issue
Creating a new world or entering a new world with both Hex Casting and Farmer's Delight installed results in a data pack error screen, with options to load the world in safe mode, with that option also bringing up the same error.

![image](https://user-images.githubusercontent.com/87587913/190932356-fae8b587-3daa-4cd4-b1b0-62831ecfcd5a.png)

**Comment by gamma-delta** [comment]
Hmm, I bet FD changed their ingredient serialization... let me take a look

**Comment by object-Object** [comment]
Need to check if this is still an issue on more recent versions.

**Comment by object-Object** [comment]
Fairly sure this works now, since we had FD in the Hexxycraft pack on 1.19. Please feel free to open a new issue if not.
