### ISSUE TITLE
The Fisherman's Gambit patterns use different indexing schemes

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#349]
Fisherman's Gambit is 1-indexed. Fisherman's Gambit II is 0-indexed.
![image](https://user-images.githubusercontent.com/37044997/207208326-7ee1bffd-5f2e-46e5-81f8-d82666c5f5fc.png)
![image](https://user-images.githubusercontent.com/37044997/207208330-fa34d124-8cfe-4592-ade6-4b14cc2f6e32.png)

**Comment by gamma-delta** [comment]
Tempted to call that intended behavior; the reason I is "1-indexed" is because it's counting the number that's popped off as 0...

**Comment by object-Object** [comment]
Fair, I guess, but in my opinion it's _so_ unintuitive for two patterns with the same name and the same sort of behaviour to use two different indexing systems. This whole thing with Fisherman's being 0 or 1 indexed changing by the update has tripped me up more times than I can count.

**Comment by object-Object** [comment]
I've set this as tentatively planned for 0.11.1, because this is the sort of thing that feels like it would be better to change when we're already breaking hexes in a bunch of other ways, than in a patch release.

**Comment by object-Object** [comment]
duplicate of #447 apparently
