### ISSUE TITLE
Conjuring light does not update block state

### ISSUE THREAD

**Issue by redstonekasi** [FallingColors/HexMod#355]
Conjuring light on a grass block that has snow on it replaces the snow but does not update the grass's state.
![image](https://user-images.githubusercontent.com/42352565/208250155-68cca8be-8366-453e-9f00-b1dcdc3ffcd2.png)

**Comment by redstonekasi** [comment]
More specifically it seems like the block state does change, only for it to revert a tick later.
![output](https://user-images.githubusercontent.com/42352565/208250657-de346b82-baf1-42e7-a481-829fdbf86cce.gif)

**Comment by object-Object** [comment]
What version of Hex Casting is this issue for? Do you know if this bug is still present in the 1.20.1 prereleases?

**Comment by redstonekasi** [comment]
I originally found this in 1.19 Hex Casting. I tested it again in both versions just now and yes, the issue is still present.

**Comment by object-Object** [comment]
Thanks! Which version exactly did you test it on? (eg. Fabric 0.11.1-7-pre-609)

**Comment by redstonekasi** [comment]
The latest, build 609, yeah.

**Comment by walksanatora** [comment]
fixed by #598
