### ISSUE TITLE
Vector exaltation/disintegration are backwards

### ISSUE THREAD

**Issue by gamma-delta** [FallingColors/HexMod#361]
It should be clockwise for construction, ccw for destruction, but they're the wrong ways

**Comment by object-Object** [comment]
uh
https://github.com/gamma-delta/HexMod/blob/main/Common/src/main/java/at/petrak/hexcasting/common/casting/RegisterPatterns.java#L57

**Comment by gamma-delta** [comment]
hm??

**Comment by object-Object** [comment]
oops dead link
https://github.com/gamma-delta/HexMod/blob/062b42cec8d5cdb8285ab76b7e240a2c0a3f8739/Common/src/main/java/at/petrak/hexcasting/common/casting/RegisterPatterns.java#L53-L55
