### ISSUE TITLE
iota limit can be breached

### ISSUE THREAD

**Issue by kristifristi** [FallingColors/HexMod#389]
in the text file is a hex that finds the nearest item and scans the area surrounding the caster for that block type, and writes all the coordinates to a list.
using the hex makes the game lag serverside forever/crash if it finds too many matching blocks.
[gamecrash or scanning hex.txt](https://github.com/gamma-delta/HexMod/files/10481792/gamecrash.or.scanning.hex.txt)
this is on 1.19.2 quilt 0.17.8 with hexcasting 0.10.3 (and hexal 0.2.6)

**Comment by object-Object** [comment]
[decoded for your viewing pleasure](https://github.com/gamma-delta/HexMod/files/10481901/decoded.txt)

**Comment by object-Object** [comment]
@Talia-12 Do you know if this is still an issue on 1.20?

**Comment by object-Object** [comment]
This should be fixed by #721.
