### ISSUE TITLE
[Suggestion] Make an actual mishap for the iota limit being breached

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#404]
Right now, if a hex runs afoul of the iota limit, it simply stops executing. This is *really* hard to debug, and not really intuitive. It'd be nice if there were at least a message in chat.

**Comment by Math321** [comment]
I'd also recommend documenting the iota limit somewhere in the book (perhaps in the list of mishaps).

**Comment by object-Object** [comment]
I think this should be fixed by #721.
