### ISSUE TITLE
Crash by repeatedly doubling list size and running out of memory

### ISSUE THREAD

**Issue by MyK00L** [FallingColors/HexMod#407]
Running on:
- minecraft 1.19.2
- quilt loader 0.17.10
- hex casting 0.10.3

I removed other mods to make sure it was not something else causing this.

![image](https://user-images.githubusercontent.com/22148361/216761295-d240a619-3565-4dc2-8e4d-d6b7feb11289.png)

[crashreport.txt](https://github.com/gamma-delta/HexMod/files/10608367/crashreport.txt)

**Comment by object-Object** [comment]
Do you know if this bug is still present in the latest 1.20.1 prereleases?

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609 AND hexcasting-forge-1.20.1-0.11.1-7-pre-609
Still occurs given the hex described originally. Assuming that's the combination pattern, this should be the same thing

[crash-2024-01-19_21.05.00-server.txt](https://github.com/FallingColors/HexMod/files/13996248/crash-2024-01-19_21.05.00-server.txt)



![Image](https://github.com/FallingColors/HexMod/assets/59519529/cb4732dd-2cee-4e72-9be6-bce7bdae183e)
