### ISSUE TITLE
Scout's with no media and no enlightenment still succeeds

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#408]
![2023-02-04_21 36 38](https://user-images.githubusercontent.com/37044997/216798641-fad51c7c-97b4-439b-bb54-514802f78963.png)

**Comment by SamsTheNerd** [comment]
i think this is an issue with all `ConstMediaAction`s. Not sure if it's changed for 0.11 though

**Comment by object-Object** [comment]
Let's test it in the 1.20.1 prereleases.

**Comment by Ch1216** [comment]
Issue still present in Fabric 0.15.10 Hex casting pre-634

**Comment by object-Object** [comment]
At least in 1.19, the issue occurs because `ConstMediaAction` calls `execute` in `Action#operate`, which runs *before* media is withdrawn in side effects.

![image](https://github.com/FallingColors/HexMod/assets/37044997/bc5938c3-0585-4a2b-9410-e5bc8e3c73d8)

I guess the fix would be to do something similar to `SpellAction`, where `ConstMediaAction` adds a side effect to actually do the work of the action?

**Comment by object-Object** [comment]
okay, I see why it doesn't already work like that - none of the side effects on 1.19 are able to modify the harness state, so they wouldn't be able to push stuff to the stack. In 1.20 we could maybe use `AttemptSpell`?

**Comment by Ch1216** [comment]
Can confirm that this Issue was fixed by the Hexcasting 0.11.2 release
