### ISSUE TITLE
Hex Book entry claims that clearing the grid with shift-click has a chance to mishap

### ISSUE THREAD

**Issue by Robotgiggle** [FallingColors/HexMod#421]
For some reason, the entry in the Hex Book talking about clearing the grid with a shift-right-click mentions that "the more media I've built up, the more likely I'll meet misfortune". This is not the case as far as I know, since shift-clicking to clear the grid always works and has never caused any issues for me. Here's the full text of the erroneous entry:
> Once I've drawn enough patterns to cast a spell, the grid will disappear as the media I've stored up is released. Holding Left Shift while using my staff will also clear the grid, if I don't mind the chance of mishap. (It seems that the more media I've built up, the more likely I'll meet misfortune.)

**Comment by object-Object** [comment]
Seems to have been fixed at some point: https://hexcasting.hexxy.media/v/0.11.1-7/1.0.dev22/en_us/#casting/101
