### ISSUE TITLE
Issues with FTB chunks + config resets 

### ISSUE THREAD

**Issue by maraxin** [FallingColors/HexMod#450]
Basically, if you try to break block in claim (FTB chunks, claim is not yours) it will work perfectly, even though it should be stopped (only fabric issue, forge has no problems).
(FTB chunks and fabric hex casting issue) if you try to place a block in other ppl claim, it will not take your block, turning it into a dupe glitch.
It seems that config in fabric version is reseted each time you restart mc/server (only disallowed spells for now).

Yeah, fabric doesn't have persistant config & it seems to not care about claims

**Comment by object-Object** [comment]
What version of Hex Casting is this issue for? Do you know if this bug is still present in the 1.20.1 prereleases?

**Comment by maraxin** [comment]
The version was latest 1.19.2 release in curseforge
For 1.20.1 I was using 0.11.1-pre-622, and I no longer can place other blocks in different ppl's claims as well as I can't place water/lava, it tells me, that it's a forbidden location, although I still can break blocks easily, as well as conjure block/light perfectly fine

**Comment by object-Object** [comment]
I believe the config persistence issue has since been fixed.

**Comment by SamsTheNerd** [comment]
This seems to be done
