### ISSUE TITLE
Attempting to mind flay anything with an invalid recipe is both free and instantly kills the target

### ISSUE THREAD

**Issue by beholderface** [FallingColors/HexMod#457]
In [at least one beta version from a few months ago](https://discord.com/channels/936370934292549712/950847275549229086/1078428894656462930), attempting to mind flay something without using a valid recipe instantly kills the target, for zero media cost.

![2023-04-30_21 47 16](https://user-images.githubusercontent.com/13290805/235389516-20601017-abf6-49b8-9ab8-f5aca0c356f7.png)

**Comment by object-Object** [comment]
What version of Hex Casting is this issue for? Do you know if this bug is still present in the 1.20.1 prereleases?

**Comment by beholderface** [comment]
This was in a 1.19.2 beta version that Alwinfy shared on discord a while back, linked in the original issue post. I have not tried this with the 1.20.1 versions.

**Comment by Ch1216** [comment]
I could not replicate this in forge 47.2.0 and hex casting pre-634

**Comment by yezhiyi9670** [comment]
In 1.20.1-forge 0.11.1-7-pre634, this will no longer instantly kill the mob. It will inflict approximately 1 damage instead.

**Comment by object-Object** [comment]
Confirmed - the code was changed over a year ago lmao.

https://github.com/FallingColors/HexMod/commit/fae9a2eecd10085504d6580ed8ccb2a8d3a325ea#diff-116fccab746508f17a696f6e9f65ef7da923c5db5933241baf393f93c7af392eL18
