### ISSUE TITLE
Suggestion: ESC cancels current pattern

### ISSUE THREAD

**Issue by Buggy123** [FallingColors/HexMod#463]
Current behavior: Pressing ESC closes entire grid, also cancelling any patterns that are being drawn, if any.
Requested behavior: Pressing ESC while drawing a pattern cancels the pattern without closing the grid.

Reasoning: Sometimes you flub a pattern, and it's easier to cancel it and redraw than to try and backtrack it and flub it further. This change makes ESC a slightly more convenient option for that.

**Comment by object-Object** [comment]
Implemented in a9c859f.
