### ISSUE TITLE
Zone Distillation: Non-Living selects Ender Dragon (Multiple times)

### ISSUE THREAD

**Issue by Nauviax** [FallingColors/HexMod#469]
Ender Dragon gets selected and shows up multiple times in return array, likely each hitbox segment or something. (Found while trying to blink nearby arrows. Ender Dragon got selected and even errored the spell; Can't blink Ender Dragon)

**Comment by object-Object** [comment]
What version of Hex Casting is this issue for? Do you know if this bug is still present in the 1.20.1 prereleases?

And just to clarify - what would be the expected behaviour here?

**Comment by SamsTheNerd** [comment]
Could probably just exclude EnderDragonPart (yarn) from all entity/zone distills? I don't see any use case where you'd want to actually grab those ?

**Comment by Nauviax** [comment]
I know at the time I was trying to get a list of all arrows nearby to iterate over, and while fighting the dragon, various "dragon" entities were making it into my list of non-living entities. Still seems to happen on version 1.19.2 (Hex Casting 0.10.3), unsure about 1.20.1 versions.

Expected behavior would be no "dragon" parts showing in the non-living zone distillation results list. Currently it seems 4 "Ender Dragon" entities are being included.

It seems dragons summoned with no AI won't contain these extra hitboxes, so make sure to summon a dragon normally if trying to reproduce.

**Comment by object-Object** [comment]
Solid, thanks for the info. I think it makes sense for the dragon parts to show up in Zone: Living (especially since it makes railguns a bit harder to implement lol), but definitely not in Non-Living.

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609 AND hexcasting-forge-1.20.1-0.11.1-7-pre-609
For the non-living distillation, it seems to grab all the segments still
For living, it just grabs one copy of the entity, presumably the hitbox, but idk

![Image](https://github.com/FallingColors/HexMod/assets/59519529/ed4ee3fc-542f-4edc-aa12-c0325a048118)
