### ISSUE TITLE
Book still refers to a "triplet" of special patterns even though the addition of Evanition means there's now four of them

### ISSUE THREAD

**Issue by Robotgiggle** [FallingColors/HexMod#477]
Pretty much what it says on the tin - the Influences section in the book mentions a triplet of strange patterns, and then lists Consideration, Introspection, Retrospection, and Evanition.

**Comment by macks2008** [comment]
It looks like Petra fixed this in 64efb43abd0c4f47a26834e597cd43daa7fb2a57, though might have to change that to "family" if any more such influences are added.

**Comment by object-Object** [comment]
thanks for the update!
