### ISSUE TITLE
(prerelease) more langfile(probably)

### ISSUE THREAD

**Issue by kristifristi** [FallingColors/HexMod#482]
boolean iotas don't show properly, neither does the invalid arguments mishap

**Comment by object-Object** [comment]
I think #616 is the invalid arguments thing? Not sure about boolean iotas, but I don't see anything wrong in recent builds.

![image](https://github.com/user-attachments/assets/cae78e5f-777c-4aaf-a317-5f0e3faacdb8)

Closing as probably fixed and also way too little detail.
