### ISSUE TITLE
(prerelease) fabric crashes on launch

### ISSUE THREAD

**Issue by kristifristi** [FallingColors/HexMod#484]
build ~~600~~ 601

[crash-2023-06-20_18.41.07-client.txt](https://github.com/gamma-delta/HexMod/files/11803620/crash-2023-06-20_18.41.07-client.txt)
[latest.log](https://github.com/gamma-delta/HexMod/files/11803621/latest.log)

**Comment by object-Object** [comment]
Is this still an issue on the latest 1.20.1 prereleases?

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609
Doesn't crash on launch, at least using this modlist

cardinal-components-api-5.2.2
cloth-config-11.1.118-fabric
fabric-api-0.91.0+1.20.1
fabric-language-kotlin-1.10.17+kotlin.1.9.22
hexcasting-fabric-1.20.1-0.11.1-7-pre-609
jei-1.20.1-fabric-15.2.0.27
Patchouli-1.20.1-83-FABRIC
paucal-fabric-1.20.1-0.6.0
Pehkui-3.7.7+1.14.4-1.20.1
