### ISSUE TITLE
low fps with many hanging scrolls

### ISSUE THREAD

**Issue by Nitero** [FallingColors/HexMod#490]
when I wanted to hang all (20) my ancient scrolls in my library the fps dropped from ~80 to ~30
without shaders its about the same thing

playing with:
hexcasting-forge-1.19.2-0.10.3.jar
Hexal
HexTweaks
Oculus
Complementary Reimagined, but as mentioned same without shader
Other mods...

**Comment by object-Object** [comment]
Should be fixed by #503 and other related changes.
