### ISSUE TITLE
Mod has missing textures and models in-game

### ISSUE THREAD

**Issue by autione** [FallingColors/HexMod#522]
ℹ I'm writing this issue in behalf of my friend, who does not have a GitHub account.

**Minecraft Version:** 1.20.1
**Loaders:** Fabric or Quilt
Built from the latest commit of the 1.20 branch (not Blanketcon)

**Other mods included (along with Hex Casting):**
- Fabric API
- Fabric Language Kotlin
- Paucal
- Patchouli
- Cloth Config

This problem occurs without optimization mods.

**Client Log:** https://mclo.gs/l1pChMT

**Comment by vgskye** [comment]
yeah the build system's.... weird, for some reason.
you need to do `runData` and `runDatagen` for fabric builds before building I believe

**Comment by object-Object** [comment]
`runXplatDatagen` also, if `runData` doesn't run that

**Comment by object-Object** [comment]
Fixed in #560 and related commits.
