### ISSUE TITLE
Slates break on Create contraptions

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#532]
https://github.com/gamma-delta/HexMod/assets/37044997/3424067a-f1f1-4f87-911f-7f88170539b2

I think this is happening because slates don't extend `FaceAttachedHorizontalDirectionalBlock`, so Create doesn't know it needs to handle them differently.

Create seems to have methods to register blocks so they'll be handled properly - I guess Hex needs to call these if Create is installed? There _is_ a `create:brittle` block tag, but without handling `isBlockAttachedTowards`, the slates just always pop off and can't be attached to contraptions at all.

https://github.com/Fabricators-of-Create/Create/blob/mc1.19/fabric/dev/src/main/java/com/simibubi/create/content/contraptions/BlockMovementChecks.java#L87-L93

**Comment by object-Object** [comment]
I'm not sure if this bug is still present in the 1.20.1 prereleases, though I'd guess it is.

**Comment by Ch1216** [comment]
Issue still persists in Forge 47.2.0 Hex casting pre-634
