### ISSUE TITLE
Cannot read null from empty scrolls/slates

### ISSUE THREAD

**Issue by Dwal32s** [FallingColors/HexMod#545]
You cannot use _Scribe's Reflection_ to read `Null` from empty scrolls or slates.

This is inconsistent with how spellbooks and foci work, as both allow players to read `Null` from their empty forms.
While scrolls and slates are not exactly the same as those other two, they are essentially the same thing when dealing with individual pattern iotas and thus should function similarly to spellbooks and foci.

Changing this would allow for easier slate writing, such as with an individual pattern copier/eraser artifact, instead of separating the artifact into an eraser and a copier.

![2023-11-24_03 18 32](https://github.com/gamma-delta/HexMod/assets/85666562/63674cfa-7118-4499-b06b-c15c00e06bdb)

**Comment by Talia-12** [comment]
Couldn't reproduce on the latest version, but that was because during the port I accidentally made it return Null for all items, regardless of whether they were ever readable. so, fixed that, and am making scrolls and slates default to returning Null

**Comment by object-Object** [comment]
@Talia-12 Resolution from Discord: (@Alwinfy fyi)

- Auditor's returns true if and only if the item is a container that has had an iota written to it.
- Scribe's Reflection mishaps if and only if Auditor's returns false.
- "Contains NULL" and "empty" are distinct states.
- All iota-holding items should behave like this, including slates and scrolls.

|Auditor|Assessor|Result
|------|------|------|
|false|false|non-container|
|false|true|empty container|
|true|false|sealed written container|
|true|true|unsealed written container|

**Comment by Talia-12** [comment]
alright, implemented that according to the desired specs now
