### ISSUE TITLE
White Sun's Zeniths at level 0 give a very big regeneration.

### ISSUE THREAD

**Issue by hatidotch** [FallingColors/HexMod#551]
White Sun's Zeniths(regeneration) at level 0 give an effect of amplifier value of -1. 
If regeneration effect's amplifier was given outside the range 0–31, remainder when it is divided by 32 is apply.
In this case, amplifier value of -1 is equrl to 31. 
Because white Sun's Zeniths at level 0 has media cost of 0, as a result player can get a very big regeneration effect with media cost of 0.

Sorry, I am not a native English speaker and this text may be ugly.

**Comment by object-Object** [comment]
What version of Hex Casting is this issue for? Do you know if this bug is still present in the 1.20.1 prereleases?

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609 AND hexcasting-forge-1.20.1-0.11.1-7-pre-609
Still present, same result as described in the original post, although I don't know the inner working- they're probably right though.
Just casting an any duration potency 0 regen will make you effectively immortal sans a one-hit kill for the duration

**Comment by hatidotch** [comment]
Sorry for the delay in replying.
I could see this bug in both 1.19.2 and 1.20.1.

**Comment by hatidotch** [comment]
I'm sorry. I'm sorry.
I closed this issue by mistake.

**Comment by macks2008** [comment]
So no more free regeneration? Or will it just be the same as potency 1?
I should probably look into less sneaky ways of protecting myself from the hostile nighttime mobs anyway, but I'll be sad if you remove/"fix" this completely, since I am generally very good at dying :-/ . Even put together a CAD together that makes use of this yesterday.
