### ISSUE TITLE
Check if cleric circle player ambit is still broken

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#561]
<img width="414" alt="image" src="https://github.com/FallingColors/HexMod/assets/37044997/18a7e13f-b019-43d5-a8c2-3a254fa34908">

**Comment by Alchristis** [comment]
Still broken; the hex works inside but not outside the spell circle

![Image](https://github.com/FallingColors/HexMod/assets/59519529/a1c2e819-d6e1-426c-82b9-30ee8e6454a1)

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609
Cleric Circle ambit works now 

hexcasting-forge-1.20.1-0.11.1-7-pre-609
Cleric Circle ambit doesn't work
To replicate, you can make the same jank spell circle as in my previous screenshot, or your own version, and see the spell cast inside but not outside of it

**Comment by object-Object** [comment]
weird!

**Comment by walksanatora** [comment]
this should be closed since it was fixed by #603
