### ISSUE TITLE
Derivation Distillation should be named Derivation Decomposition

### ISSUE THREAD

**Issue by Nauviax** [FallingColors/HexMod#562]
Specifically in the latest version of Hex Book, at https://hexcasting.hexxy.media/v/0.11.1-7/1.0.dev20/en_us/?nospoiler#patterns/lists@hexcasting:unappend

Derivation Distillation (list → list, any)
Remove the iota on the end of the list at the top of the stack, and add it to the top of the stack.

Distillation pops two and pushes one, Decomposition pops one argument and pushes two.

Not sure if this is the correct place to report this kind of thing, but #hex-bugs on the discord links here and I figured it wouldn't hurt.

**Comment by object-Object** [comment]
thanks for the report! I can confirm that this is a good place to report this kind of issue.
