### ISSUE TITLE
Request: Notary's Distillation accept two players and checks their off hand, then main hand item

### ISSUE THREAD

**Issue by dashkal16** [FallingColors/HexMod#564]
Still `entity, entity -> boolean`, but if the second entity is an EntityLiving of some sort, check their off hand, then main hand for the coin.

Use case would be a Caster's Coin (or Caster's Mark, if that freq is accepted) in your hand used as a hexxy crypto smart card.

**Comment by object-Object** [comment]
I think you're looking for https://github.com/SamsTheNerd/HexGloop/issues.

**Comment by dashkal16** [comment]
I am indeed.  Oops!
