### ISSUE TITLE
Request: Caster's Mark - Write Once Read Many signed iota holder

### ISSUE THREAD

**Issue by dashkal16** [FallingColors/HexMod#565]
Like a thought knot, but the Notary and Merchant patterns work for it.

Would serve similar use cases to cryptographicly signing a message.

**Comment by walksanatora** [comment]
notary and merchant? are those gloop patterns (I am out of the loop)

**Comment by walksanatora** [comment]
ah I see. bringing some gloop features into base hex

**Comment by object-Object** [comment]
I think you're looking for https://github.com/SamsTheNerd/HexGloop/issues.

**Comment by dashkal16** [comment]
I am indeed.  Oops!
