### ISSUE TITLE
phials do not work

### ISSUE THREAD

**Issue by bzzzzzzzzzzzzzzzzzzzzzzzzz** [FallingColors/HexMod#575]
trying to use media from a phial causes a bloodcast as if you had no media

**Comment by object-Object** [comment]
@bzzzzzzzzzzzzzzzzzzzzzzzzz why was this closed?

**Comment by bzzzzzzzzzzzzzzzzzzzzzzzzz** [comment]
> @bzzzzzzzzzzzzzzzzzzzzzzzzz why was this closed?

Not sure if you saw it already on discord or not but just in case I'm replying. It was closed because this issue was on the blanketcon version, I tested it on the latest prerelease version and it is no longer an issue (Works). If you want me to reopen I can.
