### ISSUE TITLE
bloodcasts do not work

### ISSUE THREAD

**Issue by bzzzzzzzzzzzzzzzzzzzzzzzzz** [FallingColors/HexMod#576]
spell executes -> health is consumed -> nothing happens. Bloodcasts dont work for all spells but work for patterns like architects distillation

**Comment by object-Object** [comment]
@bzzzzzzzzzzzzzzzzzzzzzzzzz why was this closed?

**Comment by bzzzzzzzzzzzzzzzzzzzzzzzzz** [comment]
> @bzzzzzzzzzzzzzzzzzzzzzzzzz why was this closed?

Not sure if you saw it already on discord or not but it was because this issue was on the blanketcon version, I tested it on the latest prerelease version and it is no longer an issue (Works).
