### ISSUE TITLE
1.20 staffcasting can draw from casting items

### ISSUE THREAD

**Issue by moonlol** [FallingColors/HexMod#582]
hexcasting-forge-1.20.1-0.11.1-7-pre-607

staff casting with casting items in inventory causes them to be used as media sources, prioritized over standard forms of media too it appears

**Comment by object-Object** [comment]
Casting items as in cyphers/trinkets/artifacts?

**Comment by moonlol** [comment]
> Casting items as in cyphers/trinkets/artifacts?

yep sorry for not being clear, i noticed this specifically with artifacts and trinkets, havent tried cyphers

**Comment by walksanatora** [comment]
looked into it a bit.
it is cause all three of these extend `ItemMediaHolder` which extends `MediaHolderItem` which implements `MediaHolderItem`
which then gets the component/capability attached to them meaning that they get their media consumed but `canProvideMedia` is set to false... but that is not respected in `MediaHelper#scanPlayerForMediaStuff` or mabey the check for `canProvideMedia` should perhaps be checked in `PlayerBasedCastEnv#extractMediaFromInventory`
