### ISSUE TITLE
1.20 anchorite's flight becomes unreliable away from world origin

### ISSUE THREAD

**Issue by moonlol** [FallingColors/HexMod#583]
the more blocks you go away from spawn the higher "base value" you need for it to even work and not stop instantly
going as little as 50 blocks from world origin is enough to make it not work 

https://github.com/FallingColors/HexMod/assets/16988779/c9af0d01-6479-4f12-b6cd-9ad960d8237a

(not pictured in video but using 50 at 50 blocks away does not work, but 51 does, let me move about ~5 blocks. albeit i was moving in parrallel with the platform rather than away from it)

hexcasting-forge-1.20.1-0.11.1-7-pre-609

**Comment by Robotgiggle** [comment]
Is this still reproducible in any way in the latest version? After som admittedly non-exhaustive testing on the current server, the bug as described above doesn't seem to be happening. I can cast Anchorite's Flight and get the correct flight radius even 5000+ blocks from spawn.

**Comment by Ch1216** [comment]
Could replicate on forge 47.2.0 and hexcasting pre-634

**Comment by object-Object** [comment]
I did a bit more investigating. Fabric has the same issue, but I guess due to how CC works, it only occurs when you reload the game (ie. deserialize the flight data).
