### ISSUE TITLE
[1.20] Key-pattern displayed on Akashic Bookshelf isn't lit correctly

### ISSUE THREAD

**Issue by Robotgiggle** [FallingColors/HexMod#587]
**Version used: 0.11.1, build 609**

The key-pattern rendered on the front of a filled Akashic Bookshelf appears nearly pitch black rather than the normal white, as though it's not receiving any lighting.

![2024-01-16_14 21 32](https://github.com/FallingColors/HexMod/assets/88736742/3bfe81a2-e7e5-4e63-ba97-7eb670d06dac)

**Comment by object-Object** [comment]
@Talia-12 any idea what's up with this?

**Comment by SamsTheNerd** [comment]
Should be fixed from inline render related stuff
