### ISSUE TITLE
[1,20] Floating patterns are way too dense in first-person

### ISSUE THREAD

**Issue by beholderface** [FallingColors/HexMod#602]
Whenever I cast a complex hex, my vision is filled with dozens of floating patterns, which are both distracting and vision-obscuring (could well be an accessibility issue, not sure). The density is fine in third-person, but it would be nice if the ones visible in first-person were much less visible (smaller, transparent, quickly-fading, idk).

![2024-02-03_22 20 45](https://github.com/FallingColors/HexMod/assets/13290805/338f3a9a-59c2-42f5-8ab1-4b7efb0dda8c)
![2024-02-03_22 21 01](https://github.com/FallingColors/HexMod/assets/13290805/6209268c-a0a5-4ffc-b7e7-ae1ea0db9dae)

**Comment by Talia-12** [comment]
Huh, the patterns aren't meant to be visible at all from first person, somethings broken there.

**Comment by object-Object** [comment]
Is this still an issue?

**Comment by navarchus** [comment]
@object-Object it has not been an issue at all for me while I've been working on recent stuff, in fact I don't think I've seen any glyphs in first person

**Comment by object-Object** [comment]
Closing as it seems to have been fixed a while ago; will reopen if someone can provide repro steps.
