### ISSUE TITLE
overcasting fails if you wear armor, even unenchanted vanilla leather armor

### ISSUE THREAD

**Issue by macks2008** [FallingColors/HexMod#622]
in 1.20 (as tested on "HexxyTest"), overcasting breaks if you wear armor. Any armor. I know it's supposed to cancel the cast if the damage gets negated somehow, but it's supposed to be piercing standard attribute-based armor right?

**Comment by walksanatora** [comment]
I think this is due to how dammage types were changed to being mostly data-driven in 1.20. this should be a easy fix I could look into
