### ISSUE TITLE
main branch depends on paucal via libs/ folder in all projects when paucal is now on blamejared maven.

### ISSUE THREAD

**Issue by walksanatora** [FallingColors/HexMod#624]
changes to be made:
edit :comon, :fabric, :forge's build.grades to point to maven.blamejared.com for paucal instead of the jar included in repo
and remove the paucal jars from the libs/ folders

**Comment by object-Object** [comment]
@walksanatora is this fixed by #627?

**Comment by walksanatora** [comment]
correct it was solved by #627
