### ISSUE TITLE
Post media extraction handler

### ISSUE THREAD

**Issue by walksanatora** [FallingColors/HexMod#625]
I was just talking with @munelitjolty on discord and I noticed something that may be simple to add and slightly usefull (unless I am missing a better way)
so in their 1.19 addon they add a new [DiscoveryHandler](https://github.com/MoonlitJolteon/hex-keys-addon/blob/main/common/src/main/java/dev/munebase/hexkeys/casting/HexKeysDiscoverers.java) for media items in the klein chest (bigger enderchest which can also extract media from)
and the only ways I can see to replicate this behaviour in 1.20.1 is
1. mixin to the `getItemsForExtraction` on relevant casting environments (mixins are... not a good idea and can break compatibility and I feel like ther has to be a better way)
2. add a `ExtractMedia` casting env component (always runs before env media extraction, which means it also always eats from the klein chest which is not preferable as it is meant to be secondary and less efficent)

my idea: make a `PostExtractMedia` env component that is nearly the same as `ExtractMedia` but runs *after* env media extraction occurs

**Comment by object-Object** [comment]
@walksanatora was this implemented by #626?

**Comment by walksanatora** [comment]
correct this was implemented by #626
