### ISSUE TITLE
1.20 Forge crash on death when origins is installed (related to #559?)

### ISSUE THREAD

**Issue by Aquaeyes** [FallingColors/HexMod#632]
[crash-2024-03-09_08.24.39-client.txt](https://github.com/FallingColors/HexMod/files/14544331/crash-2024-03-09_08.24.39-client.txt)

```
Description: Ticking entity

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?] {re:mixin}
	at at.petrak.hexcasting.forge.cap.adimpl.CapClientCastingStack.tickClientPlayer(CapClientCastingStack.java:22) ~[hexcasting-forge-1.20.1-0.11.1-7-pre-620.jar%23151!/:0.11.1-7-pre-620] {re:classloading}
	at at.petrak.hexcasting.forge.cap.adimpl.__CapClientCastingStack_tickClientPlayer_PlayerTickEvent.invoke(.dynamic) ~[hexcasting-forge-1.20.1-0.11.1-7-pre-620.jar%23151!/:0.11.1-7-pre-620] 
```

Error occurs with Forge 47.2.0, Hex Casting 0.11.1-7-pre-620, PAUCAL 0.6.0-pre-118, kotlinforforge-4.10.0-all, Caelus API 3.1.0+1.20, Patchouli 1.20.1-84-FORGE. Issue occurs around about one in three times when dying, my reproduction steps was to spawn, fly about 100 blocks away from spawn, then do /kill. The issue occurs with origins, but as soon as it's removed, even leaving it's dependencies in place, there's no issue (as far as I can tell)

**Comment by SamsTheNerd** [comment]
seems related to #559

**Comment by Aquaeyes** [comment]
With origins:
![image](https://github.com/FallingColors/HexMod/assets/10935410/68db145a-78bd-4490-8017-95c2317481f9)
Without origins:
![image](https://github.com/FallingColors/HexMod/assets/10935410/6c298015-6667-4eed-b361-48157cf89401)
It looks like the issue is with isDeadOrDying? :oc
<img width="499" alt="image" src="https://github.com/FallingColors/HexMod/assets/10935410/bee498b7-74b0-4e8b-88d0-a5bd94e4b0ab">

**Comment by Aquaeyes** [comment]
Logging evt.player.getHealth()

Without Origins:
![image](https://github.com/FallingColors/HexMod/assets/10935410/bda95ac8-5e5c-48e8-9859-512023a5ebd7)
With Origins:
![image](https://github.com/FallingColors/HexMod/assets/10935410/b4f94ac1-7af8-4e33-b484-06eeb49c1078)

Seems semi-common that getHealth and isDeadOrDying will return 20.0 or true still after the /kill command goes through, but only for 1 or 2 calls afterwards at max so far. However, this doesn't cause a crash without Origins (Forge) installed.

**Comment by Aquaeyes** [comment]
Issue does not occur with only Calio.
