### ISSUE TITLE
Spell Circle Unable to use Recharge

### ISSUE THREAD

**Issue by eleksploded** [FallingColors/HexMod#638]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-629

### Modloader version

Forge 47.2.0

### Modpack info

Custom made pack.

### The latest.log file

https://mclo.gs/B2HZ1IO

### Issue description

Spell circles are unable to use the recharge hex to recharge a phial in a players offhand.

![2024-03-20_23 20 44](https://github.com/FallingColors/HexMod/assets/8619498/09c8cdd2-bb79-4e31-b387-80cbc89edb26)
![2024-03-20_23 42 33](https://github.com/FallingColors/HexMod/assets/8619498/8fc7150b-1689-4a4d-b4dd-3edea72b88c6)

### Steps to reproduce

Create a Spell circle that grabs amethyst in its bounds in zone distillation, and uses thoth's to cast recharge with each of them. It will fail saying a rechargeable item is needed in your other hand, even if you are holding an empty phial (no matter which hand or whats in the other hand).

**Comment by eleksploded** [comment]
Ok so I decided to go through and figure out why. [OpRecharge](https://github.com/FallingColors/HexMod/blob/65a07575137282a14e528045de0ddd7663e6d95a/Common/src/main/java/at/petrak/hexcasting/common/casting/actions/spells/OpRecharge.kt#L26) calls [getHeldItemToOperateOn](https://github.com/FallingColors/HexMod/blob/65a07575137282a14e528045de0ddd7663e6d95a/Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java#L371) which uses [getPrimaryStacks](https://github.com/FallingColors/HexMod/blob/65a07575137282a14e528045de0ddd7663e6d95a/Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java#L340). However in the Circle's casting environment, [getPrimaryStacks](https://github.com/FallingColors/HexMod/blob/65a07575137282a14e528045de0ddd7663e6d95a/Common/src/main/java/at/petrak/hexcasting/api/casting/eval/env/CircleCastEnv.java#L167) always returns an empty list, so no matter what the caster is holding, the spell circle will never be able to access it.

**Comment by VbifVbif** [comment]
Where you download hexcasting for 1.20.1 forge?

**Comment by object-Object** [comment]
thanks for looking into it!
@Talia-12 any thoughts on this issue? I see you left a TODO about using adjacent inventories - is that still planned?

**Comment by Talia-12** [comment]
I implemented it with adjacent inventories and presented it, petra said she was planning on doing it with a specific in-circle component (like a directrix but stores items), so the adjacent inventories version didn't get merged in
