### ISSUE TITLE
GTP uses setPos instead of TeleportTo making it hard to make a immovable entity

### ISSUE THREAD

**Issue by walksanatora** [FallingColors/HexMod#641]
### Modloader

Fabric

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-619

### Modloader version

fabric 0.15.3 + loader

### Modpack info

N/A

### The latest.log file

N/A

### Issue description

OpTeleport uses `setPos` if the entity being teleported is not "sticky" which means that it does use teleportTo

### Steps to reproduce

1. make a entity
2. override TeleportTo
```kt
class MRE(entityType: EntityType<out MRE>, level: Level) : LivingEntity(entityType, level)  {
    override fun teleportTo(...) = false
}
```
3. use GTP to teleport the entity
4. entity gets moved

### Other information

mabey marking the entity as sticky would fix this. idk why we use teleport to when if it is not sticky we dis-mount any entities that are riding it (and dismount it from whatever it is riding)

**Comment by walksanatora** [comment]
edit: just found out a tag exists to make a entity un-teleportable

**Comment by object-Object** [comment]
@walksanatora since that tag exists, is this still an issue?

**Comment by walksanatora** [comment]
Nope
