### ISSUE TITLE
Finish implementing alternate item textures

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#643]
From @walksanatora and @Talia-12 on Discord:

<img width="414" alt="image" src="https://github.com/FallingColors/HexMod/assets/37044997/ab5a3658-07eb-47f2-acea-911aecd7719e">
<img width="414" alt="image" src="https://github.com/FallingColors/HexMod/assets/37044997/f2bf0894-938c-4fa0-b53c-8d61fea3bed0">

Although this is an enhancement, I'm prioritizing it higher than other new stuff because I feel like we should try to avoid releasing half-finished features if possible.

**Comment by object-Object** [comment]
Current ideas:
- Just document the current pattern for cycling item variants
- Add a stonecutter-like block for this purpose
- Aly: "mixin amethyst bud's random tick to check for an item frame & transform the item it grows into"

**Comment by gamma-delta** [comment]
Probably just document the pattern? That would be the easiest. I do think the pattern method is a bit janky but I'd rather not be blocking on a vanity decoration thing of all things.

**Comment by gamma-delta** [comment]
Wow being in charge is great, I am pinged for my attention and I deign to give a response, and my underlings skitter around to do my bidding. I see why they hire interns
