### ISSUE TITLE
Add OpThanos to the pattern registry

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#652]
As of 488c6feac, it seems like OpThanos, despite being implemented, is not actually used anywhere.
![image](https://github.com/FallingColors/HexMod/assets/37044997/77bbf5b8-1258-42d7-b648-07f705e24fba)

**Comment by walksanatora** [comment]
in 1.19 this was the "meta evals left" pattern. what was the pattern for it back then? (or has it remained unused for it's entire lifetime?)
