### ISSUE TITLE
Thoth's Gambit not working with Mindflay?

### ISSUE THREAD

**Issue by wompking** [FallingColors/HexMod#657]
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

Forge 43.3.8

### The latest.log file

https://pastebin.com/XSE4iLKj

### Issue description

Somehow, Thoth's Gambit is breaking with Flay Mind. No clue why.

### Steps to reproduce

- Set up a list containing at least one vector pointing to an amethyst block
- Set up a list containing at least one journeyman villager
- Set up a pattern list containing: [Undertaker's, Selection Dist., Rotation II, Selection Dist., Flay Mind]
- Set up a list containing the indices you want to iterate over (e.g. [0,1])
- Run Thoth's

Expected behavior:
- All villagers are flayed, the lists are removed, [] is pushed

Actual behavior:
- Only the first villager is flayed, the stack isn't mutated at all (!), Thoth's Gambit turns grey, an error is thrown in the console

My setup is slightly different, but produces the same bug:
<img width="901" alt="Screenshot 2024-04-25 at 19 30 27" src="https://github.com/FallingColors/HexMod/assets/30229570/11877306-8f9a-46c7-860a-5a5a55011fe2">

### Other information

I modified a few mindflay recipes with KubeJS, but that shouldn't be a problem (hopefully). Looks like the problem is internal. I looked through the issues before posting and couldn't find anything related to this.

**Comment by object-Object** [comment]
@SamsTheNerd I see a hexgloop mixin in the logs 👀

**Comment by SamsTheNerd** [comment]
Maybe related to samsthenerd/hexgloop#58 having a log is helpful though. I'll look into it soon

**Comment by wompking** [comment]
Can confirm that HexGloop is the problem. Tried the exact same setup just now (same mods, sans HexGloop) and it worked.

**Comment by object-Object** [comment]
Ok, I'll go ahead and close this since it's an external issue.
