### ISSUE TITLE
List can be infinitely doubled in size, bypassing the iota count limit

### ISSUE THREAD

**Issue by yezhiyi9670** [FallingColors/HexMod#662]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-efc8899

### Modloader version

47.2.30

### The latest.log file

https://gist.github.com/yezhiyi9670/b5c3c9e8a6140b237785d4f284dfca31

### Issue description

As I know, Nature limits how many iotas I can hold in my mind (stack). If such limits is exceeded, excessive iotas will be deleted from my stack or turned into garbage. However, I can somehow double the size of list infinitely (see below).

A "runaway" spell using this can eventually cause OutOfMemory crash.

### Steps to reproduce

1. Make a list with at least 1 element.
2. Run the list through Gemini Decomposition and Additive Distillation repeatedly.
   ❎ Note that the size of the list may exceed 1000 and reach incredibly high numbers.

Additionally, this runaway spell can cause OutOfMemory crash:

![Screenshot of spell](https://github.com/FallingColors/HexMod/assets/39194383/f1c4b73e-a0da-4dec-b806-2dcd00adfced)

- Pattern list: [Mind's Reflection]
- Pattern list: [Jester's Gambit, **Gemini Decomposition**, **Addition Distillation**, Jester's Gambit, Gemini Decomposition, Hermes' Gambit]
- Gemini Decomposition
- Hermes' Gambit

**Comment by walksanatora** [comment]
if I had to guess. the ListArithmatic doesen't check size when adding.

**Comment by yezhiyi9670** [comment]
This may be a duplicate of #407.
