### ISSUE TITLE
Gemini Gambit's Shame On You mishap can kill the player even when executed in a spell circle

### ISSUE THREAD

**Issue by yezhiyi9670** [FallingColors/HexMod#663]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-efc8899

### Modloader version

47.2.30

### Issue description

The Gemini Gambit can kill a player if the player attempts to copy an iota over 1000 times. It can even kill the "caster" (the one who triggers a Toolsmith or Fletcher Impetus or is bound to a Cleric Impetus) if executed in a spell circle.

This does not make much sense since in the case of a spell circle, the "caster" is not the one who meant to copy an iota for too many times. Additionally, with some mods like Create, a spell circle can be started with a specific player as the "caster" even without that player's presence at the scene, allowing for some definitely-not-so-fun pranks.

### Steps to reproduce

![Screenshot](https://github.com/FallingColors/HexMod/assets/39194383/978527b6-fd5f-4273-9ce7-027cf851799a)

1. Make a spell circle with the following spells:
   - Nullary Reflection
   - Number Reflection: 10
   - Number Reflection: 4
   - Power Distillation
   - Gemini Gambit
2. Start the spell circle with a player (for example myself) as the "caster".
3. Wait for the spell to complete.
   ❎ The "caster" will be killed when Gemini Gambit is executed.

### Other information

Expected (or desired) behavior: the spell should break the impetus or part of the spell circle instead of killing the caster.

**Comment by object-Object** [comment]
Related: #665
