### ISSUE TITLE
Drawing patterns game crash

### ISSUE THREAD

**Issue by egdod333** [FallingColors/HexMod#666]
### Modloader

Fabric

### Minecraft version

1.18.2

### Hex Casting version

0.9.6

### Modloader version

Fabric Loader 0.15.10

### The latest.log file

https://mclo.gs/WsFZwlB

### Issue description

The mouse drag event on the pattern drawing screen causes a game crash.

### Steps to reproduce

1. Open wand ui
2. Draw any pattern

**Comment by object-Object** [comment]
Duplicate of #164, see [this comment](https://github.com/FallingColors/HexMod/issues/164#issuecomment-1179446592) for the solution.
