### ISSUE TITLE
1.20.1 New player unable to get Blind Diversion advancement

### ISSUE THREAD

**Issue by starji** [FallingColors/HexMod#667]
### Modloader

Fabric

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-634

### Modloader version

Fabric: Loader 0.15.9 + API 0.92.1+1.20.1

### Modpack info

https://github.com/walksanatora/HexxyTestPack/blob/main/modpack.zip

### Issue description

I looked but didn't see this bug listed yet.  Apologies if I missed it.  A fresh player using the 1.20.1 builds for hex casting (at least on build 634) cannot get the `Blind Diversion` advancement or further.  This blocks them from the ability to use health for hexcasting.

When a player attempts to cast a great spell, the great spell just works, instead of fizzliing out like in 1.19

### Steps to reproduce

1. Start a new single player or server world
2. Cast a great spell

Expected: Get Blind Diversion and need to take 19 damage in a single spell to get the next advancement
Actual: Great Spell succeeds, no advancement achieved.

**Comment by macks2008** [comment]
Thanks for reporting thIs @starji; I'd been meaning to report it but once you have a workaround like the datapack we've been using on Chloe's server it's easy to let these things slide.

Yeah we've been working around this one for a while. About time someone thought to report it and followed through on the thought *slightly embarrassed grin*

**Comment by walksanatora** [comment]
this no longer occurs in development. no clue when/where it was fixed (tested in forge/fabric build 648)

**Comment by SamsTheNerd** [comment]
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/fc4bf028-4e5a-4340-ba5a-91188b5fb738">
can't reproduce on latest build. tried on server as well just to make sure. 

also no idea when/how/where this got fixed? best guess is some addon was causing issues?
