### ISSUE TITLE
Hexal + Hex Casting crash

### ISSUE THREAD

**Issue by ElenaNya** [FallingColors/HexMod#677]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-634 and 637

### Modloader version

Forge: 47.2.17 (also 47.2.30)

### Modpack info

(screenshot)

### The latest.log file

https://mclo.gs/9YA2vNT

### Issue description

When casting wisp / it hits the ground / interacts with something - server / single world crashes, if I use mod Neruina, it will not crash the server, but the one who used the spell, is it possiblee to find out what is wrong? 

Petrak helped me, told that it could be because of new Hex Сasting version, and Hexal hasn't been updated for a long time, is there any solution to this?

I just couldn't find if there is somewhere to download an older version than 0.11.1-7, I'm not looking for a quick fix, in general just wanted to let you know that this problem exists 😗

### Steps to reproduce

1. Install the same mods.
2. Launch the game -> single world / server.
3. Draw symbols.
4. Try to use them.
5. Crash.

### Other information

![image](https://github.com/FallingColors/HexMod/assets/94359925/713b661e-9689-4c8e-afca-26b38cc8a450)
![image](https://github.com/FallingColors/HexMod/assets/94359925/9ce2e5e8-0a8a-40ab-b7ce-72ed0554f40f)
![image](https://github.com/FallingColors/HexMod/assets/94359925/c4147e53-0d62-4d67-91bf-dcd2eabc34dd)

Crash-report:
https://mclo.gs/BAvHBUW

---

also another one symbol that can cause a crash:
![image](https://github.com/FallingColors/HexMod/assets/94359925/5658112a-6754-4d07-97ec-010c2e187533)
Log: https://mclo.gs/B12grs4
Crash-report: https://mclo.gs/BaYgDdZ

**Comment by walksanatora** [comment]
what petrak said is correct. your hexcasting is too new for hexal in 1.20
you need to download a patched version (I have forge/fabric ones in [Hexxytest](https://github.com/walksanatora/HexxyTestPack)
forge would be in the s2 branch, fabric is in the main branch

**Comment by ElenaNya** [comment]
> what petrak said is correct. your hexcasting is too new for hexal in 1.20 you need to download a patched version (I have forge/fabric ones in [Hexxytest](https://github.com/walksanatora/HexxyTestPack) forge would be in the s2 branch, fabric is in the main branch

[crash-2024-06-07_13.13.14-server.txt](https://github.com/user-attachments/files/15737570/crash-2024-06-07_13.13.14-server.txt)

[latest.log](https://github.com/user-attachments/files/15737572/latest.log)

Crashes with latest - https://github.com/walksanatora/HexxyTestPack/releases

**Comment by ElenaNya** [comment]
The only thing we've changed is the new version of gekolib.

**Comment by walksanatora** [comment]
ah you are in forge. I am working on fixing it right now. (non-mod deps are annoying)

**Comment by object-Object** [comment]
Closing as this is apparently not a Hex issue. In general, if you're having trouble with an addon, please open an issue on that addon's GitHub first, not this one :)

**Comment by ElenaNya** [comment]
> Closing as this is apparently not a Hex issue. In general, if you're having trouble with an addon, please open an issue on that addon's GitHub first, not this one :)

oh, thought this would be more appropriate, sorry 😮

> ah you are in forge. I am working on fixing it right now. (non-mod deps are annoying)

thank you! Good luck! Can you please indicate in the changelog when you will fix it? 💖
