### ISSUE TITLE
Workaround For Truename Privacy

### ISSUE THREAD

**Issue by Albedo413** [FallingColors/HexMod#694]
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3.jar

### Issue description

I found i was able to forcibly steal a truename by getting a reference to it, and writing it on a focal amulet, and it does not say amything about invading their soul's privacy

### Steps to reproduce

1.get a reference to a player
2.wear a focal pendant
3.Cast memento's gambit

**Comment by SamsTheNerd** [comment]
This sounds like a hex gloop issue rather than a base hex issue
