### ISSUE TITLE
Empty Links

### ISSUE THREAD

**Issue by Roseplate** [FallingColors/HexMod#709]
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

43.4.0

### Issue description

Logging off a server while linked to a wisp causes the index it was on to be permanently attached to null and causes it to be unlinkable, any additional wisps will take up the index after it. The empty links return null when phonebook purification is used and trying to unlink the index doesn't work (and doesn't take any media, if that helps). As a side note; a "clear all links" spell would be nice.
This doesn't seem reproducible singleplayer but I did manage to recreate it again on the same server intentionally.

### Steps to reproduce

Create a wisp
Link yourself to it
Log off
Log on

**Comment by object-Object** [comment]
I don't see how this is related to Hex Casting. Open an issue on Hexal instead, please.

**Comment by Roseplate** [comment]
My bad, I thought I was on the hexal github.
