### ISSUE TITLE
Using Amethyst Dust on hanging scroll only affects local client's view

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [FallingColors/HexMod#712]
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

43.4.0

### Issue description

When using Amethyst Dust on a hanging scroll to display extra information for drawing the pattern stored on it, the change only seems to occur for the client using the dust, it does not show up for anyone else. Other players still cannot use dust on the scroll themselves, meaning they have to pick up the scroll, place it back down, and then use the dust on it.

### Steps to reproduce

1. Get scroll
2. Write any pattern to it
3. Place scroll on wall
4. Use Amethyst dust on scroll
5. View scroll from perspective of a second player

**Comment by TinyDeskEngineer06** [comment]
Strange, it's working fine now. I don't know if it had something to do with an update or if it was just a weird one-off bug.

**Comment by SamsTheNerd** [comment]
Were you using gloop either time? It has some scroll effecting bits, possible it's a glitch from that.

**Comment by TinyDeskEngineer06** [comment]
No, I only installed gloop for the first time today.

**Comment by object-Object** [comment]
Closing as it seems to be working now (?)
