### ISSUE TITLE
Archer's Distillation does not hit non-solid blocks like saplings

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [FallingColors/HexMod#713]
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

43.4.0

### Issue description

Archer's Distillation is supposed to return the position of the block that would be highlighted by a player looking at a specific position and angle, but it seems to pass through blocks non-solid to the player that can still otherwise be highlighted, such as saplings. Instead, the pattern returns the position of any blocks _behind_ the non-solid block, or NULL if there aren't any.

### Steps to reproduce

1. Place non-solid but highlightable block anywhere
2. Look at block and cast "Raycast Mantra"
3. Resulting iota will either be a vector not pointing towards highlighted block or will be NULL

**Comment by object-Object** [comment]
I'm not sure this counts as a bug? That's just how the raycast patterns work. I believe there are addons that add raycasts to hit non-solid blocks.
