### ISSUE TITLE
Possibility to create build for 1.21?

### ISSUE THREAD

**Issue by ekarlsso** [FallingColors/HexMod#717]
### Describe the feature

I was wondering would it be possible to create a build for 1.21? Not sure how big a change this is from API point of view.

At least I  can promise test runs if the build is created.

**Comment by SamsTheNerd** [comment]
We're still working on 1.20, sorry

**Comment by SamsTheNerd** [comment]
1.21 changes a lot behind the scenes especially with regards to items. It likely wont be the most straightforward port up.

**Comment by ekarlsso** [comment]
Thanks for the reply. I will close the issue then :)

**Comment by ryleu** [comment]
probably best to keep this open if it's something y'all plan to do eventually:tm:

**Comment by walksanatora** [comment]
I mean there is. https://github.com/FallingColors/HexMod/tree/devel/port-1.21
