### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by Entropy159** [FallingColors/HexMod#752]
### Modloader

Fabric

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Issue description

I am trying to make some small modifications to the source of this mod, but I am getting an error when trying to build the mod.
```
> Configure project :Common
SpongePowered Vanilla 'GRADLE' Toolset Version '0.2.1-SNAPSHOT'
Targeting Minecraft '1.19.2' on a 'JOINED' platform

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Common'.
> Failed to notify project evaluation listener.
   > 'void org.gradle.api.artifacts.repositories.InclusiveRepositoryContentDescriptor.includeGroupAndSubgroups(java.lang.String)'
```
I'm not entirely sure why this is happening.

### Steps to reproduce

1. Download the 1.19 branch
2. Run ./gradlew build

**Comment by object-Object** [comment]
Gradle needs to be updated. See https://github.com/FallingColors/HexMod/pull/688. We probably won't do this on the 1.18 or 1.19 branch since active development has moved to 1.20.
