### ISSUE TITLE
Gradle build is not working

### ISSUE THREAD

**Issue by Wanzet** [FallingColors/HexMod#770]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

main-branch

### Issue description

Gradle cant compile your main branch mod version because Cardinal Components files are 404: https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-entity/5.2.1/cardinal-components-entity-5.2.1.jar

**Comment by SamsTheNerd** [comment]
It seems to be building just fine on the jenkins with the most recent commit? The url you linked loads just fine for me, that's the one that was giving you a 404?

**Comment by Wanzet** [comment]
> It seems to be building just fine on the jenkins with the most recent commit? The url you linked loads just fine for me, that's the one that was giving you a 404?

Here's the ones:  Could not find cardinal-components-entity-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.1).
     Searched in the following locations:
         https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-entity/5.2.1/cardinal-components-entity-5.2.1.jar
 Could not find cardinal-components-item-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-item:5.2.1).
     Searched in the following locations:
         https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-item/5.2.1/cardinal-components-item-5.2.1.jar
 Could not find cardinal-components-block-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-block:5.2.1).
     Searched in the following locations:
         https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-block/5.2.1/cardinal-components-block-5.2.1.jar
 Could not find cardinal-components-base-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.1).
     Searched in the following locations:
         https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-base/5.2.1/cardinal-components-base-5.2.1.jar
 
Screenshot from browser: 
![123](https://github.com/user-attachments/assets/147be6b5-7f75-4cbf-8b79-e7e4a265ac5e)

Anyway I've already just found developer's built release for 1.20.1 version

**Comment by Wanzet** [comment]
> > It seems to be building just fine on the jenkins with the most recent commit? The url you linked loads just fine for me, that's the one that was giving you a 404?
> 
> Here's the ones: Could not find cardinal-components-entity-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.1). Searched in the following locations: https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-entity/5.2.1/cardinal-components-entity-5.2.1.jar Could not find cardinal-components-item-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-item:5.2.1). Searched in the following locations: https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-item/5.2.1/cardinal-components-item-5.2.1.jar Could not find cardinal-components-block-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-block:5.2.1). Searched in the following locations: https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-block/5.2.1/cardinal-components-block-5.2.1.jar Could not find cardinal-components-base-5.2.1.jar (dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.1). Searched in the following locations: https://maven.ladysnake.org/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-base/5.2.1/cardinal-components-base-5.2.1.jar
> 
> Screenshot from browser: ![123](https://private-user-images.githubusercontent.com/73957764/380425710-147be6b5-7f75-4cbf-8b79-e7e4a265ac5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk1MDUsIm5iZiI6MTcyOTk0OTIwNSwicGF0aCI6Ii83Mzk1Nzc2NC8zODA0MjU3MTAtMTQ3YmU2YjUtN2Y3NS00Y2JmLThiNzktZTdlNGEyNjVhYzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDEzMjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTE0NjlkNjQxMjAzODcwZjQ5YjU5NTAwMTU2N2I0OTBmNzBjZjEyYzRmNmIzY2Y4YjI0YzlkYmMzYWVmZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wdQKZ095FSCbMLxr-TI7-XnQ669g7BryHfwy7BiLXWU)
> 
> Anyway I've already just found developer's built release for 1.20.1 version

Now I've found that last two links are working in browser but not in git bash / cmd, taht's kinda weird

**Comment by object-Object** [comment]
this happens intermittently. the ladysnake maven kinda just sucks, it goes down like this fairly often. I don't think we can really do anything about it.
