### ISSUE TITLE
Casting Great Spells without a player

### ISSUE THREAD

**Issue by squimbo** [FallingColors/HexMod#772]
### Describe the feature

A way for Casting Items and Spell Circles to cast great spells independently of the player. This could be as simple as allowing any pattern written by an enlightened individual to be used by anyone or anything, or adding a new impetus or enhanced cypher/trinket/artifact for casting great spells.

The current best solution we have is a Cleric Impetus, but that only works if the bound player is online, which stops being the case if they log off of a server (which may be a bug in itself)

### Additional context

Mainly for making teleportation circles and automating the Mind Flaying process, but I'm sure other people could come up with all sorts of creative uses for this.

**Comment by SamsTheNerd** [comment]
done with enlightened circles.

**Comment by squimbo** [comment]
Guh ???
