### ISSUE TITLE
Pattern to get type of iota

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [FallingColors/HexMod#775]
### Describe the feature

It would be very useful to have a pattern that pops one iota of any type, and pushes an iota representing the type of the input iota. In combination with Equality Distillation and Augur's Exaltation, such a pattern would be a very powerful tool and allow for type checking in hexes.

### Additional context

An example use case would be a teleportation hex that can use both a vector and an entity iota for its destination, with the behavior differing depending on what is provided to it.

**Comment by SamsTheNerd** [comment]
I believe hexal or moreiotas has this. I would not be opposed to moving it into base hex, but I'm not sure it needs to be.
