### ISSUE TITLE
Impetus Vanishes after breaking

### ISSUE THREAD

**Issue by nuclearmayhem1** [FallingColors/HexMod#781]
### Modloader

Fabric

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

Fabric - 0.16.7

### Modpack info

https://drive.google.com/file/d/14i3MyxvhqJ4Y4HP15bqA4x-3BdVtG_9a/view?usp=sharing

### The latest.log file

https://mclo.gs/2Yy6psb

### Issue description

Breaking an impetus of any kind causes it to reappear as a ghost block momentarily once, then vanish forever afterwards.

### Steps to reproduce

1. Place impetus
2. Break impetus

**Comment by SamsTheNerd** [comment]
gloop issue

**Comment by object-Object** [comment]
known hexgloop issue, go yell at @SamsTheNerd to release the fix
