### ISSUE TITLE
Screen freeze when rendering patterns?

### ISSUE THREAD

**Issue by Aquaeyes** [FallingColors/HexMod#795]
### Modloader

Quilt

### Minecraft version

1.20.1

### Hex Casting version

0.11.7-pre-677+

### Modloader version

QFAPI 7.6.0+0.92.2, Loader 0.27.0

### The latest.log file

https://mclo.gs/VhrvY5i

### Issue description

(No crash)

Game rendering freezes upon rendering patterns in a variety of circumstances, no additional information printed into logs.

### Steps to reproduce

1. Draw Consideration with a staff
2. Draw any other pattern
3. Freeze

https://github.com/user-attachments/assets/40800584-47a1-4381-abaf-24d575e464cb

Alternatively,
1. Open the hex notebook to any page with a rendered pattern on it
2. Freeze

<img width="592" alt="Screenshot 2024-11-24 at 11 40 22 am" src="https://github.com/user-attachments/assets/320b7593-063f-4f0f-bde1-1e485b9fd1e3">

Alternatively,
1. Hover over a scroll in the inventory
2. Freeze

<img width="1312" alt="Screenshot 2024-11-24 at 11 47 51 am" src="https://github.com/user-attachments/assets/5dffb6ae-699f-467d-9605-ba2789817f73">

Interestingly enough, I was able to press 4 whilst hovered over it, and when I restarted, it was in my hotbar. Given I can still hear game audio, this implies it's only the rendering that's frozen, not the game itself.

Alternatively, weirdly enough,
1. Switch to 676
2. Do *not* freeze when using the staff, or hovering over the ancient scroll
3. Do not freeze when copying the ancient scroll over to a large scroll, not when hovering over it
4. Freeze entirely when placing the large/small scroll down, seemingly causing the game to freeze as well (seemingly before the scroll is even placed?)
???
5?. test world now freezes upon loading, even when updated to 698
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/e0f047c8-b179-4838-8de0-388344316abc">

Presumably this one is a different bug given it's occurring in versions before the other ones are?

Alternatively, rendering it in text will likely freezing, but I've no way of testing that currently (I don't know how to put them in chat askjdf). [entity:pig] and other inline features work fine without freezing.

Update: oh yep that does it too, frozen

<img width="1312" alt="Screenshot 2024-11-24 at 12 19 24 pm" src="https://github.com/user-attachments/assets/3c0a89ff-fa3f-47d2-bd93-87863d0f53da">

### Other information

OS: MacOS Ventura 13.1 (22C65)

**Comment by SamsTheNerd** [comment]
Given the behavior on 676 this is almost certainly an issue with texture rendering.

**Comment by Aquaeyes** [comment]
...long shot weird question, but would awt be being used?

https://github.com/aratakileo/emogg/issues/13#issuecomment-1666353811

**Comment by SamsTheNerd** [comment]
it sure is! that'd do it
