### ISSUE TITLE
Patchouli issue

### ISSUE THREAD

**Issue by F-708** [FallingColors/HexMod#809]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.2

### Modloader version

47.3.12

### The latest.log file

https://pastebin.com/wiePrHsC

### Issue description

![image](https://github.com/user-attachments/assets/d7a98177-b405-48fb-b1f4-903e030b1d18)
Error in guide book

**Comment by object-Object** [comment]
this is an issue with HexGender. you can tell because it says HexGender in the screenshot. please open an issue on their GitHub instead ^^
